package com.example.eDoc.dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import com.example.eDoc.dao.mappers.IMapResultSetIntoEntity;
import com.example.eDoc.dao.uow.IUnitOfWork;
import com.example.eDoc.model.Lekarz;


public class LekarzRepository extends RepositoryBase<Lekarz> implements ILekarzRepository {
	
	public LekarzRepository(Connection connection,
			IMapResultSetIntoEntity<Lekarz> mapper,
			IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	@Override
	protected String tableName() {
		return "lekarz";
	}
	
	protected String createTableSql() {
			return "CREATE TABLE lekarz ("
					+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
					+ "name VARCHAR(45) NULL,"
					+ "surname VARCHAR(45) NULL,"
					+ "adress VARCHAR(45) NULL,"
					+ "zipcode VARCHAR(45) NULL,"
					+ "city VARCHAR(45) NULL,"
					+ "region VARCHAR(45) NULL,"
					+ "country VARCHAR(45) NULL,"
					+ "phone VARCHAR(45) NULL,"
					+ "email VARCHAR(45) NULL,"
					+ "password VARCHAR(45),"
					+ "specialization VARCHAR(45) NULL"
					+ ")";

	}
	
	@Override
	protected String insertSql() {
		return "INSERT INTO lekarz(name,surname,adress,zipcode,city,region,country,phone,email,password,specialization) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE pacjent set name=?, surname=?, adress=?, zipcode=?, city=?, region=?, country=?, phone=?, email=?, password=?, specialization=? WHERE id=?";
	}


	@Override
	protected void setupInsert(Lekarz entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
		insert.setString(3, entity.getAdress());
		insert.setString(4, entity.getZipcode());
		insert.setString(5, entity.getCity());
		insert.setString(6, entity.getRegion());
		insert.setString(7, entity.getCountry());
		insert.setString(8, entity.getPhone());
		insert.setString(9, entity.getEmail());
		insert.setString(10, entity.getPassword());
		insert.setString(11, entity.getSpecialization());
		
	}

	@Override
	protected void setupUpdate(Lekarz entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		update.setString(3, entity.getAdress());
		update.setString(4, entity.getZipcode());
		update.setString(5, entity.getCity());
		update.setString(6, entity.getRegion());
		update.setString(7, entity.getCountry());
		update.setString(8, entity.getPhone());
		update.setString(9, entity.getEmail());
		update.setString(10, entity.getPassword());
		update.setString(11, entity.getSpecialization());
		update.setInt(12, entity.getId());
		
}

	public List<Lekarz> withName(String name) {
		// TODO Auto-generated method stub
		return null;
	}

}
