package com.example.eDoc.dao;

import java.sql.Connection;
import java.sql.SQLException;

import com.example.eDoc.dao.mappers.*;
import com.example.eDoc.dao.uow.IUnitOfWork;
import com.example.eDoc.model.*;

import java.util.*;

public class PacjentRepository extends RepositoryBase<Pacjent> implements IPacjentRepository {
	
	
	public PacjentRepository(Connection connection,
			IMapResultSetIntoEntity<Pacjent> mapper,
			IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	@Override
	protected String tableName() {
		return "pacjent";
	}
	
	protected String createTableSql() {
			return "CREATE TABLE pacjent ("
					+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
					+ "name VARCHAR(45) NULL,"
					+ "surname VARCHAR(45) NULL,"
					+ "adress VARCHAR(45) NULL,"
					+ "zipcode VARCHAR(45) NULL,"
					+ "city VARCHAR(45) NULL,"
					+ "region VARCHAR(45) NULL,"
					+ "country VARCHAR(45) NULL,"
					+ "phone VARCHAR(45) NULL,"
					+ "email VARCHAR(45) NULL,"
					+ "password VARCHAR(45),"
					+ "age INT NULL,"
					+ "PESEL VARCHAR(45) NULL"
					+ ")";

	}
	
	@Override
	protected String insertSql() {
		return "INSERT INTO pacjent(name,surname,adress,zipcode,city,region,country,phone,email,password,age,PESEL) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE pacjent set name=?, surname=?, adress=?, zipcode=?, city=?, region=?, country=?, phone=?, email=?, password=?, age=?, PESEL=? WHERE id=?";
	}


	@Override
	protected void setupInsert(Pacjent entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
		insert.setString(3, entity.getAdress());
		insert.setString(4, entity.getZipcode());
		insert.setString(5, entity.getCity());
		insert.setString(6, entity.getRegion());
		insert.setString(7, entity.getCountry());
		insert.setString(8, entity.getPhone());
		insert.setString(9, entity.getEmail());
		insert.setString(10, entity.getPassword());
		insert.setInt(11, entity.getAge());
		insert.setString(12, entity.getPESEL());
		
	}

	@Override
	protected void setupUpdate(Pacjent entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		update.setString(3, entity.getAdress());
		update.setString(4, entity.getZipcode());
		update.setString(5, entity.getCity());
		update.setString(6, entity.getRegion());
		update.setString(7, entity.getCountry());
		update.setString(8, entity.getPhone());
		update.setString(9, entity.getEmail());
		update.setString(10, entity.getPassword());
		update.setInt(11, entity.getAge());
		update.setString(12, entity.getPESEL());
		update.setInt(13, entity.getId());
		
}

	public List<Pacjent> withName(String name) {
		// TODO Auto-generated method stub
		return null;
	}
	
}